import { test } from 'node:test';
import assert from 'node:assert/strict';
import { existsSync, mkdtempSync, readFileSync, rmSync, writeFileSync, mkdirSync } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { ensureGithubAction } from '../githubAction.ts';

function makeDir(): string {
  return mkdtempSync(path.join(tmpdir(), 'ds-viewer-action-'));
}

test('writes .github/workflows/ds-viewer.yml with the exact pinned-action content and "npm ci" when there is no lockfile at all', () => {
  const dir = makeDir();
  const written = ensureGithubAction(dir);
  const workflowPath = path.join(dir, '.github', 'workflows', 'ds-viewer.yml');
  assert.deepEqual(written, [workflowPath]);
  const content = readFileSync(workflowPath, 'utf8');
  assert.match(content, /^name: DS Viewer\n/);
  assert.match(content, /on:\n  pull_request:\n/);
  assert.match(content, /actions\/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4\.2\.2/);
  assert.match(content, /actions\/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4\.1\.0/);
  assert.match(content, /node-version: '20'/);
  assert.match(content, /- run: npm ci\n/);
  assert.match(content, /npx ds-viewer doctor --ci/);
  rmSync(dir, { recursive: true, force: true });
});

test('writes "npm ci" when package-lock.json is present', () => {
  const dir = makeDir();
  writeFileSync(path.join(dir, 'package-lock.json'), '{}');
  ensureGithubAction(dir);
  const content = readFileSync(path.join(dir, '.github', 'workflows', 'ds-viewer.yml'), 'utf8');
  assert.match(content, /- run: npm ci\n/);
  assert.ok(!content.includes('pnpm'));
  rmSync(dir, { recursive: true, force: true });
});

test('writes a pnpm/action-setup step with version 10 and "pnpm install --frozen-lockfile" when pnpm-lock.yaml is present and package.json has no packageManager field', () => {
  const dir = makeDir();
  writeFileSync(path.join(dir, 'pnpm-lock.yaml'), '');
  ensureGithubAction(dir);
  const content = readFileSync(path.join(dir, '.github', 'workflows', 'ds-viewer.yml'), 'utf8');
  assert.match(
    content,
    /actions\/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4\.2\.2\n\s+- uses: pnpm\/action-setup@ea17c68df8912ef543352723c149a84f56e3d413 # v6\.1\.0\n\s+with:\n\s+version: 10\n\s+- uses: actions\/setup-node/,
  );
  assert.match(content, /- run: pnpm install --frozen-lockfile\n/);
  rmSync(dir, { recursive: true, force: true });
});

test('writes a pnpm/action-setup step with the version read from package.json\'s own packageManager field', () => {
  const dir = makeDir();
  writeFileSync(path.join(dir, 'pnpm-lock.yaml'), '');
  writeFileSync(path.join(dir, 'package.json'), JSON.stringify({ name: 'proj', packageManager: 'pnpm@9.1.0' }));
  ensureGithubAction(dir);
  const content = readFileSync(path.join(dir, '.github', 'workflows', 'ds-viewer.yml'), 'utf8');
  assert.match(content, /- uses: pnpm\/action-setup@ea17c68df8912ef543352723c149a84f56e3d413 # v6\.1\.0\n\s+with:\n\s+version: 9\n/);
  rmSync(dir, { recursive: true, force: true });
});

test('writes "yarn install --frozen-lockfile" (no corepack step) when yarn.lock is a v1 lockfile', () => {
  const dir = makeDir();
  writeFileSync(path.join(dir, 'yarn.lock'), '# yarn lockfile v1\n\n\nleft-pad@^1.0.0:\n  version "1.3.0"\n');
  ensureGithubAction(dir);
  const content = readFileSync(path.join(dir, '.github', 'workflows', 'ds-viewer.yml'), 'utf8');
  assert.match(content, /- run: yarn install --frozen-lockfile\n/);
  assert.ok(!content.includes('--immutable'));
  assert.ok(!content.includes('corepack'));
  assert.ok(!content.includes('pnpm'));
  rmSync(dir, { recursive: true, force: true });
});

test('writes a "corepack enable" step then "yarn install --immutable" when yarn.lock is a Yarn Berry lockfile', () => {
  const dir = makeDir();
  writeFileSync(path.join(dir, 'yarn.lock'), '# This file is generated by running "yarn install" inside your project.\n__metadata:\n  version: 8\n');
  ensureGithubAction(dir);
  const content = readFileSync(path.join(dir, '.github', 'workflows', 'ds-viewer.yml'), 'utf8');
  assert.match(content, /- run: corepack enable\n\s+- run: yarn install --immutable\n/);
  rmSync(dir, { recursive: true, force: true });
});

test('creates .github/workflows/ when neither folder exists yet', () => {
  const dir = makeDir();
  assert.equal(existsSync(path.join(dir, '.github')), false);
  ensureGithubAction(dir);
  assert.equal(existsSync(path.join(dir, '.github', 'workflows', 'ds-viewer.yml')), true);
  rmSync(dir, { recursive: true, force: true });
});

test('is idempotent: a second call writes nothing and the file is unchanged', () => {
  const dir = makeDir();
  ensureGithubAction(dir);
  const before = readFileSync(path.join(dir, '.github', 'workflows', 'ds-viewer.yml'), 'utf8');
  const written = ensureGithubAction(dir);
  assert.deepEqual(written, []);
  assert.equal(readFileSync(path.join(dir, '.github', 'workflows', 'ds-viewer.yml'), 'utf8'), before);
  rmSync(dir, { recursive: true, force: true });
});

test('never overwrites a workflow file a user already has at that exact path', () => {
  const dir = makeDir();
  mkdirSync(path.join(dir, '.github', 'workflows'), { recursive: true });
  writeFileSync(path.join(dir, '.github', 'workflows', 'ds-viewer.yml'), 'name: Custom\n');
  const written = ensureGithubAction(dir);
  assert.deepEqual(written, []);
  assert.equal(readFileSync(path.join(dir, '.github', 'workflows', 'ds-viewer.yml'), 'utf8'), 'name: Custom\n');
  rmSync(dir, { recursive: true, force: true });
});
